### ISSUE TITLE
Discord 邀请

### ISSUE THREAD

**Issue by kylesliu** [Rominez/league-of-Chinese-programmers#1]
>你好，我看见你了在996ICU项目上的热情，但是迫于GitHub交流不便，所以想邀请您进入我们Discord，方便交流。
[Discord Link](https://discord.gg/6E3kzEG)

**Comment by Rominez** [comment]
> 
> 
> > 你好，我看见你了在996ICU项目上的热情，但是迫于GitHub交流不便，所以想邀请您进入我们Discord，方便交流。
> > [Discord Link](https://discord.gg/6E3kzEG)

谢邀，没有接触过 discord，眼前也没个翻墙工具怎么整？

**Comment by netsman1030** [comment]
怎么在内地上discord
104.16.248.144   dl.discordapp.net
104.16.60.37   gateway.discord.gg
104.16.11.231  status.discordapp.com
104.16.9.231    cdn.discordapp.com
104.16.59.5  discordapp.com
104.16.248.144 media.discordapp.net
104.16.249.144 images-ext-2.discordapp.net
104.16.248.144 images-ext-1.discordapp.net
151.101.78.214  static-cdn.jtvnw.net

Hosts添加这些信息
