### ISSUE TITLE
小透明提建议

### ISSUE THREAD

**Issue by 996icu-support** [Rominez/league-of-Chinese-programmers#5]
新注册了小马甲，因为只想当个小透明，希望大家不要介意。

小透明提出一些建议和问题，供大家参考

目前大家呼声最高的是程序员自己建立一个公司信息披露网站，主要公布以下信息：

- 公司的上班时间，是否能调休，加班是否给工资 （这一块应归属于公司管理制度，但是这一块实为大家最关心的，所以单独列出来）
- 公司信息及结构（是否是一个真实的公司，会不会变成一个跑路公司）
- 公司实际财务状况（财务状况是否稳定，能否持续发工资）
- 公司管理制度（人文关怀、公司环境气氛）

个人建议：还需要开放出相关法律渠道保护正在受侵害的人，比如公司拖延发放工资、加班不给加班费等等，总结出一个针对某种情况的切实维护个人权益的流程路径。

##  首要任务，聚集起想实际行动的群众

由于目前996-icu 鱼龙混杂，广告贴很多，提出实际行动的却还没有实际建立起来，甚至可能会出现重复活动，目前首要任务应该是聚集起大家。避免重复无效的活动。

## 扩大广大群众

这不是程序员的狂欢，而应扩大到各个行业，所有忍受996，997等加班剥削制度的群众。形成团结的力量。

##  有组织有效率的实施

确定各个小组产品、前端、后端、运维、运营

产品需要考虑的是，如何建立起公开、透明、公平的体制。
前端、后端具体使用什么技术框架
后期可能会出现的运维、运营问题。

## 产品问题

其实最让大家纠结的是如何避免水军注入、如何确保信息准确？
但其实，我们要想好这是一个长期战役，目前最应该做的是有一个平台，可以供大家提供信息，当流量足够大。如何提高公开性、透明性、公平力度，都可以先放到之后。
一步有一步的工作，希望大家不要着急，先做出东西，再慢慢重构、优化。
因为不实际具体做出来，观望一下，实在是纸上谈兵。

个人以为，产品目前主要是：

- 披露公司信息（名称、地址、法人）
- 公司上班时间
- 调休制度
- 加班费
- 个人发表评论

之后再慢慢优化；

## 费用问题
这个是无法避免的问题。因为要购买服务器。
资金如何筹措？如何建立公开透明制度？

个人目前粗陋建议：
- 资金首先众筹；
- 其次，指派一人或多人管理，这些人的信息需要公开，以防携款跑路
- 需要有人监督账目

## 其他问题
- 网站是国内服务器还是国外服务器好？   个人以为，为了避免被封，以国外服务器为主，国内先部署一个试试水。

- 协作沟通工具的确定

## 工作分配问题：

个人以为目前分为以下工作：

- 宣传组：需要有人在996icu不停发布招募贴，聚集有志之士。同时扩大广大群众基础。
- 产品组：讨论需求，收集需求，给出版本计划和原型图
- 前后端组： 讨论好使用什么技术、确定技术框架
- 运维组：部署服务器，以及可能会出现的大规模并发量等等
- 管理组： 协调大家工作时间
- 收集数据组：
      -  利用现有工具，收集企业公司信息，为数据导入做准备；以及先整理出一部分数据展示
      - 投票决定，产品功能设计

大家可以根据自己的实际情况选择不同小组。

当然，这些建议还不够成熟，有其他建议的欢迎留言补充。

希望大家能坚持下去，这是一个长期战役，做好心理准备。

**牢记目标是反对996，不进icu！**

由于目前996-icu项目不允许新账号创建issue，欢迎大家，将内容转发出去，让更多人看到。

希望最后我们大家可以形成有组织、有计划地去实现我们的目标！！！！！！！
  

干货贴
+ [关于 反996制度运动 的一些实际性建议](https://github.com/996icu/996.ICU/issues/15612)
+ [全国人大代表浙江部分名单及手机电话号](https://github.com/996icu/996.ICU/issues/16219)
+ [成立996公司查询网站！！！ ](https://github.com/996icu/996.ICU/issues/9422)
+ [建议搞个可自由提交和投票的 996 公司名单（附原型）](https://github.com/996icu/996.ICU/issues/642)
+ [拿出实际行动来，用技术捍卫我们的权益。《区块链996名单白皮书》【求补充】](https://github.com/996icu/996.ICU/issues/16902)
+ [Design A Software License Of Labor Protection -- 996ICU License / 申明一种证书,如MIT,只有非996的公司才能用.这样以后有牛的项目,就可以带这个证书,996公司不能用.](https://github.com/996icu/996.ICU/pull/15642)

**Comment by 996icu-support** [comment]
[Shall we talk on Slack or Telegram?](https://github.com/996icu/996.ICU/issues/3)

**Comment by 996icu-support** [comment]
[955 不加班的公司名单](https://github.com/formulahendry/955.WLB)

**Comment by zhoushuren** [comment]
可以收集一下有时间做的小伙伴,建个群。本人最近没上班。闲着有时间先报个名。

**Comment by 996icu-support** [comment]
[程序员找工作黑名单，换工作和当技术合伙人需谨慎啊 ](https://github.com/shengxinjing/programmer-job-blacklist)

**Comment by 996icu-support** [comment]
[icu996_poll_result](https://github.com/swuecho/icu996_poll_result)

**Comment by 996icu-support** [comment]
[it_blacklist_company](https://github.com/lxl0928/it_blacklist_company)

**Comment by 996icu-support** [comment]
close是被采纳还是.....？

**Comment by LinFeng1987** [comment]
想法不错

**Comment by Rominez** [comment]
我也不知道咋就close了，刚注意到....不愧是小透明
